### ISSUE TITLE
Archi-Lab_Mandrill 2018.0.2 "Launch Window" button

### ISSUE THREAD

**Issue by MatteoCapoferri** [BadMonkeysTeam/Mandrill#48]
Dynamo crashes when clicking on "Launch Window" button of the Report Window node.

Revit 2018
Dynamo 1.3.0.875
Archi-lab_Mandrill 2018.0.2 (through Dynamo package manager)
![164](https://user-images.githubusercontent.com/36993906/39361393-9b6ff348-49f8-11e8-8f76-abdfa939ee9c.JPG)

Method not found: 'EO.WebBrowser.WebView EO.WebBrowser.Wpf.WebControl.get_WebView()'.

   at Mandrill.ChromeWindow.MandrillWindow..ctor()
   at Mandrill.ChromeWindow.MandrillWindowNodeViewCustomization.CreateNewWindow()
   at Mandrill.ChromeWindow.MandrillWindowNodeModel.ShowMessage(Object obj)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

**Comment by ksobon** [comment]
@MatteoCapoferri can you show me the contents of this folder: `C:\Users\username\AppData\Roaming\Dynamo\Dynamo Revit\1.3\packages\Archi-lab_Mandrill\bin`

**Comment by MatteoCapoferri** [comment]
![165](https://user-images.githubusercontent.com/36993906/39363490-e1ce546c-4a00-11e8-942c-d1edd3db0486.JPG)

here you are thanks

**Comment by ksobon** [comment]
OK this looks good. Can you do me a favor and make sure that the input into that node is NOT null? 

![image](https://user-images.githubusercontent.com/529781/39367062-b9b7bea2-4a03-11e8-8440-a6fab2354026.png)

Basically go backwards a little to make sure that you are getting a proper report object.

**Comment by MatteoCapoferri** [comment]
No. The input should be correct.
Thanks for your help.

![166](https://user-images.githubusercontent.com/36993906/39368964-67a53ff0-4a11-11e8-9d7b-e8ab61b8a387.JPG)

**Comment by DrewJarvisSolidCAD** [comment]
I am getting the same issue
![capture](https://user-images.githubusercontent.com/34753077/46230261-f57e5d00-c31c-11e8-81ef-c22582cfe679.png)
![capture2](https://user-images.githubusercontent.com/34753077/46230296-121a9500-c31d-11e8-8ba8-a5122721f7b9.PNG)

Method not found: 'EO.WebBrowser.WebView EO.WebBrowser.Wpf.WebControl.get_WebView()'.

   at Mandrill.ChromeWindow.MandrillWindow..ctor()
   at Mandrill.ChromeWindow.MandrillWindowNodeViewCustomization.CreateNewWindow()
   at Mandrill.ChromeWindow.MandrillWindowNodeModel.ShowMessage(Object obj)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

![capture3](https://user-images.githubusercontent.com/34753077/46230586-e6e47580-c31d-11e8-9eaa-4c4c62976d31.PNG)

**Comment by wassimj** [comment]
Hi Konrad,
I am still getting the same issue with the new version downloaded from the package manager (2019.2.0)
Failed to resolve LoadLibrary.

   at EO.Internal.jh.b.d()
   at EO.Internal.jh.b.a(String[] A_0, String A_1, String A_2, String A_3, String A_4)
   at EO.Internal.jh.a(Boolean& A_0, String[] A_1, String A_2, String A_3, String A_4, String A_5)
   at EO.Internal.jh.a(String[] A_0, String A_1, String A_2, String A_3, String A_4)
   at EO.Internal.jh.o.c()
   at EO.Internal.jh.o.f()
   at EO.Internal.jh.l()
   at EO.Internal.jh.a(Boolean& A_0, String[] A_1, String A_2, String A_3, String A_4, String A_5)
   at EO.Internal.jh.a(String[] A_0, String A_1, String A_2, String A_3, String A_4)
   at EO.Internal.awp.e()
   at EO.WebEngine.Engine.Start()
   at EO.Internal.awp.a()
   at EO.Internal.cm..ctor(WebView A_0)
   at EO.WebBrowser.WebView.w()
   at EO.WebBrowser.WebView.b(IntPtr A_0, Boolean A_1)
   at EO.WebBrowser.Wpf.WebControl.a.a(HandleRef A_0)
   at System.Windows.Interop.HwndHost.BuildWindow(HandleRef hwndParent)
   at System.Windows.Interop.HwndHost.BuildOrReparentWindow()
   at System.Windows.Interop.HwndHost.OnSourceChanged(Object sender, SourceChangedEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.PresentationSource.UpdateSourceOfElement(DependencyObject doTarget, DependencyObject doAncestor, DependencyObject doOldParent)
   at System.Windows.PresentationSource.OnVisualAncestorChanged(DependencyObject uie, AncestorChangedEventArgs e)
   at System.Windows.UIElement.OnVisualAncestorChanged(Object sender, AncestorChangedEventArgs e)
   at System.Windows.Media.Visual.ProcessAncestorChangedNotificationRecursive(DependencyObject e, AncestorChangedEventArgs args)
   at System.Windows.Media.Visual.AddVisualChild(Visual child)
   at System.Windows.Controls.Decorator.set_Child(UIElement value)
   at EO.WebBrowser.Wpf.WebControl.OnApplyTemplate()
   at System.Windows.FrameworkElement.ApplyTemplate()
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   at System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Documents.AdornerDecorator.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Border.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Window.MeasureOverrideHelper(Size constraint)
   at System.Windows.Window.MeasureOverride(Size availableSize)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Interop.HwndSource.SetLayoutSize()
   at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   at System.Windows.Window.SetRootVisual()
   at System.Windows.Window.SetRootVisualAndUpdateSTC()
   at System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at Mandrill.ChromeWindow.MandrillWindowNodeViewCustomization.CreateNewWindow()
   at Mandrill.ChromeWindow.MandrillWindowNodeModel.ShowMessage(Object obj)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   at System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   at MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   at MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   at System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   at System.Windows.Application.RunDispatcher(Object ignore)
   at System.Windows.Application.RunInternal(Window window)
   at DynamoSandbox.DynamoCoreSetup.RunApplication(Application app)

![image](https://user-images.githubusercontent.com/6302909/51868520-1a73f280-2346-11e9-97cd-4e1cd0cbbcc9.png)

**Comment by wassimj** [comment]
@ksobon I am running Dynamo Sandbox version 2.0.1.5055
I am attaching the simplest definition I could create that crashes it. It crashes consistently by the way. I can never see the window. But creating an HTML works absolutely fine. Have not tried PDF.

![image](https://user-images.githubusercontent.com/6302909/51890323-a9f3c280-2393-11e9-9071-146a2f4a0e6d.png)

Dynamo definition (Link expires 15 February 2019).
https://cf-my.sharepoint.com/:u:/g/personal/jabiw_cardiff_ac_uk/EQqDSSCQw35CvDkl3shHGQsBSIgy5oXAar1P9oVeSTA8qg?e=dN5BkH

**Comment by ksobon** [comment]
@wassimj it looks like your issue is the same as reported here: https://github.com/BadMonkeysTeam/Mandrill/issues/57 I just posted a potential solution. Can you give it a try?

**Comment by wassimj** [comment]
Will do. Next week. Thanks

Dr. Wassim Jabi, Reader
Course Director, MSc Computational Methods in Architecture
Director of Student Recruitment and Admissions
Welsh School of Architecture
Cardiff University
Bute Building
King Edward VII Avenue
Cardiff CF10 3NB
Wales U.K.
Tel: +44 (0) 29 2087 5891
E-mail: jabiw@cardiff.ac.uk
The University welcomes correspondence in Welsh or English.
Dr. Wassim Jabi, Darllenydd
Cyfarwyddwr Cwrs, MSc Dulliau Cyfrifiadurol ym maes Pensaernïaeth
Cyfarwyddwr Recriwtio Myfyrwyr a Derbyniadau
Ysgol Pensaernïaeth Cymru
Prifysgol Caerdydd
Adeilad Bute
Rhodfa’r Brenin Edward VII
Caerdydd CF10 3NB
Cymru D.U.
Ffôn: +44 (0) 29 2087 5891
E-bost: jabiw@caerdydd.ac.uk
Mae'r Brifysgol yn croesawu gohebiaeth yn Gymraeg neu'n Saesneg.

**Comment by ksobon** [comment]
@wassimj actually just install the latest from package manager: 

![image](https://user-images.githubusercontent.com/529781/57054087-5ded3e00-6c60-11e9-8b61-980b8389f859.png)

**Comment by ksobon** [comment]
@wassimj there is yet another version of Mandrill that was just released. Please update to 2021.1.1. I will close this issue since I don't think it will be a problem with this latest release anymore.
