### ISSUE TITLE
Issue with "Launch Window" Crashing Dynamo and Revit

### ISSUE THREAD

**Issue by MDP-BM** [BadMonkeysTeam/Mandrill#57]
Hello,

I downloaded a script from Konrad Sobon for Parsing Warnings into a nice little graph. I am using the latest Dynamo Revit version 2.0.2. and latest Dynamo Core. When I first opened the script I had to fix a lot of unresolved nodes. Once I got that all figured out, I ran the script. When I select the Launch Window, it instantly crashes Revit and Dynamo. He requested that I post the issue here. 

http://archi-lab.net/digging-through-revit-warnings-to-find-meaning/

Here is the crash info:
Failed to resolve LoadLibrary.

   at EO.Internal.jh.b.d()
   at EO.Internal.jh.b.a(String[] A_0, String A_1, String A_2, String A_3, String A_4)
   at EO.Internal.jh.a(Boolean& A_0, String[] A_1, String A_2, String A_3, String A_4, String A_5)
   at EO.Internal.jh.a(String[] A_0, String A_1, String A_2, String A_3, String A_4)
   at EO.Internal.jh.o.c()
   at EO.Internal.jh.o.f()
   at EO.Internal.jh.l()
   at EO.Internal.jh.a(Boolean& A_0, String[] A_1, String A_2, String A_3, String A_4, String A_5)
   at EO.Internal.jh.a(String[] A_0, String A_1, String A_2, String A_3, String A_4)
   at EO.Internal.awp.e()
   at EO.WebEngine.Engine.Start()
   at EO.Internal.awp.a()
   at EO.Internal.cm..ctor(WebView A_0)
   at EO.WebBrowser.WebView.w()
   at EO.WebBrowser.WebView.b(IntPtr A_0, Boolean A_1)
   at EO.WebBrowser.Wpf.WebControl.a.a(HandleRef A_0)
   at System.Windows.Interop.HwndHost.BuildWindow(HandleRef hwndParent)
   at System.Windows.Interop.HwndHost.BuildOrReparentWindow()
   at System.Windows.Interop.HwndHost.OnSourceChanged(Object sender, SourceChangedEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.PresentationSource.UpdateSourceOfElement(DependencyObject doTarget, DependencyObject doAncestor, DependencyObject doOldParent)
   at System.Windows.PresentationSource.OnVisualAncestorChanged(DependencyObject uie, AncestorChangedEventArgs e)
   at System.Windows.UIElement.OnVisualAncestorChanged(Object sender, AncestorChangedEventArgs e)
   at System.Windows.Media.Visual.ProcessAncestorChangedNotificationRecursive(DependencyObject e, AncestorChangedEventArgs args)
   at System.Windows.Media.Visual.AddVisualChild(Visual child)
   at System.Windows.Controls.Decorator.set_Child(UIElement value)
   at EO.WebBrowser.Wpf.WebControl.OnApplyTemplate()
   at System.Windows.FrameworkElement.ApplyTemplate()
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   at System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Documents.AdornerDecorator.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Border.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Window.MeasureOverrideHelper(Size constraint)
   at System.Windows.Window.MeasureOverride(Size availableSize)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Interop.HwndSource.SetLayoutSize()
   at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   at System.Windows.Window.SetRootVisual()
   at System.Windows.Window.SetRootVisualAndUpdateSTC()
   at System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at Mandrill.ChromeWindow.MandrillWindowNodeViewCustomization.CreateNewWindow()
   at Mandrill.ChromeWindow.MandrillWindowNodeModel.ShowMessage(Object obj)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

I don't know if this matters but the create report says D3jslib.report but the Launch Window says empty dictionary.
![2019-04-26_10-14-24](https://user-images.githubusercontent.com/50025628/56821659-37687680-680c-11e9-9b5f-73098e513ff0.png)

On a side note, I am only getting about 40% of warnings. Some of the warnings have system info that I cannot replicate in the Rating Library file. Some of them look like this: _EA 443: It is not possible to calculate the flow since the flow direction mismatch. Please check flow direction on all equipment in this system._

Thanks
Jason

**Comment by ksobon** [comment]
@MDP-BM do you by any chance have Windows 10 Pro version 1809 installed?

**Comment by MDP-BM** [comment]
> @MDP-BM do you by any chance have Windows 10 Pro version 1809 installed?

I do.
![2019-04-26_10-27-33](https://user-images.githubusercontent.com/50025628/56822332-f40f0780-680d-11e9-860e-9fdb97182e74.png)

**Comment by ksobon** [comment]
Can you give this a try: https://drive.google.com/file/d/1OPVA3irOQdaWVGxiYd-6EV3oZYDLEXXv/view?usp=sharing

Just make sure to first UNBLOCK the ZIP, then unzip the contents and replace in your Packages folder. I will publish that to the Package Manager once I know it solved the issue.

**Comment by ksobon** [comment]
@MDP-BM just for references this seems to be a known issue related to Windows 10 and that specific release. 

![image](https://user-images.githubusercontent.com/529781/56824119-a00f1d80-6823-11e9-934a-0d93e404db6f.png)

**Comment by MDP-BM** [comment]
> Can you give this a try: https://drive.google.com/file/d/1OPVA3irOQdaWVGxiYd-6EV3oZYDLEXXv/view?usp=sharing
> Just make sure to first UNBLOCK the ZIP, then unzip the contents and replace in your Packages folder. I will publish that to the Package Manager once I know it solved the issue.

It still crashed.

Operation is not valid due to the current state of the object.

   at EO.Internal.jh.a(Boolean& A_0, String[] A_1, String A_2, String A_3, String A_4, String A_5)
   at EO.Internal.jh.a(String[] A_0, String A_1, String A_2, String A_3, String A_4)
   at EO.Internal.jh.o.c()
   at EO.Internal.jh.o.f()
   at EO.Internal.jh.l()
   at EO.Internal.jh.a(Boolean& A_0, String[] A_1, String A_2, String A_3, String A_4, String A_5)
   at EO.Internal.jh.a(String[] A_0, String A_1, String A_2, String A_3, String A_4)
   at EO.Internal.awp.e()
   at EO.WebEngine.Engine.Start()
   at EO.Internal.awp.a()
   at EO.Internal.cm..ctor(WebView A_0)
   at EO.WebBrowser.WebView.w()
   at EO.WebBrowser.WebView.b(IntPtr A_0, Boolean A_1)
   at EO.WebBrowser.Wpf.WebControl.a.a(HandleRef A_0)
   at System.Windows.Interop.HwndHost.BuildWindow(HandleRef hwndParent)
   at System.Windows.Interop.HwndHost.BuildOrReparentWindow()
   at System.Windows.Interop.HwndHost.OnSourceChanged(Object sender, SourceChangedEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.PresentationSource.UpdateSourceOfElement(DependencyObject doTarget, DependencyObject doAncestor, DependencyObject doOldParent)
   at System.Windows.PresentationSource.OnVisualAncestorChanged(DependencyObject uie, AncestorChangedEventArgs e)
   at System.Windows.UIElement.OnVisualAncestorChanged(Object sender, AncestorChangedEventArgs e)
   at System.Windows.Media.Visual.ProcessAncestorChangedNotificationRecursive(DependencyObject e, AncestorChangedEventArgs args)
   at System.Windows.Media.Visual.AddVisualChild(Visual child)
   at System.Windows.Controls.Decorator.set_Child(UIElement value)
   at EO.WebBrowser.Wpf.WebControl.OnApplyTemplate()
   at System.Windows.FrameworkElement.ApplyTemplate()
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Grid.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at MS.Internal.Helper.MeasureElementWithSingleChild(UIElement element, Size constraint)
   at System.Windows.Controls.ContentPresenter.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Documents.AdornerDecorator.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Controls.Border.MeasureOverride(Size constraint)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Window.MeasureOverrideHelper(Size constraint)
   at System.Windows.Window.MeasureOverride(Size availableSize)
   at System.Windows.FrameworkElement.MeasureCore(Size availableSize)
   at System.Windows.UIElement.Measure(Size availableSize)
   at System.Windows.Interop.HwndSource.SetLayoutSize()
   at System.Windows.Interop.HwndSource.set_RootVisualInternal(Visual value)
   at System.Windows.Window.SetRootVisual()
   at System.Windows.Window.SetRootVisualAndUpdateSTC()
   at System.Windows.Window.SetupInitialState(Double requestedTop, Double requestedLeft, Double requestedWidth, Double requestedHeight)
   at System.Windows.Window.CreateSourceWindow(Boolean duringShow)
   at System.Windows.Window.ShowHelper(Object booleanBox)
   at Mandrill.ChromeWindow.MandrillWindowNodeViewCustomization.CreateNewWindow()
   at Mandrill.ChromeWindow.MandrillWindowNodeModel.ShowMessage(Object obj)
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

The EOWP info is above my head at this time.

**Comment by ksobon** [comment]
Would you be able to do a quick call with me? I would want to see your screen. That would better allow me to be able to debug this issue.

**Comment by MDP-BM** [comment]
Sure, what do you want to use for that screensharing?

**Comment by ksobon** [comment]
@MDP-BM thanks for getting on a call with me. It looks like Mandrill is not crashing because of an issue with Mandrill (since we were able to build a graph and launch it just fine), but it has to be caused by corrupt data/old components in that sample file you downloaded from my blog. Again it was created over 2 years ago, and a lot has changed in Dynamo. First and foremost Dynamo is no longer XML based but JSON. I would recommend re-building that graph from scratch in Dynamo 2.0 to make sure that there isn't any issues with how the file is parsed, or how components are updated from 1.3 to 2.0 version. 

Good luck!
