### ISSUE TITLE
Launch Window crash

### ISSUE THREAD

**Issue by nicebikemate** [BadMonkeysTeam/Mandrill#58]
Prelude, I have read through most of the threads regarding this but it seems unique, to my layman's eyes at least. 

Worth mentioning here that i'm using latest version of Dynamo, Revit 2020.1 on windows 10 pro, version 1903, build 18362.476.

What did you do?
(Fill in here)
Attempted to run Launch Window for Mandrill by Archi-lab

What did you expect to see?
(Fill in here)
Window should pop up showing a donut chart

What did you see instead?
(Fill in here)
Nothing, Dynamo just crashes out.

What packages or external references (if any) were used?
(Fill in here)
Mandrill
Clockwork
NodeModelCharts

Stack Trace
(From the Dynamo crash window select 'Details' -> 'Copy' and paste here)
The process cannot access the file 'C:\Users\RobertS\AppData\Roaming\Dynamo\Dynamo Revit\2.2\packages\Archi-lab_Mandrill\bin\eowp.exe' because it is being used by another process.

at EO.Internal.ji.a(String A_0, Byte[] A_1)
at Mandrill.ChromeWindow.MandrillWindow..ctor()
at Mandrill.ChromeWindow.MandrillWindowNodeViewCustomization.CreateNewWindow()
at Mandrill.ChromeWindow.MandrillWindowNodeModel.ShowMessage(Object obj)
at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
at System.Windows.Controls.Primitives.ButtonBase.OnClick()
at System.Windows.Controls.Button.OnClick()
at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
at System.Windows.Input.InputManager.ProcessStagingArea()
at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
OS: Microsoft Windows NT 10.0.18362.0
CLR: 4.0.30319.42000
Dynamo: 2.2.1.5175

**Comment by nicebikemate** [comment]
addendum: it also crashes on print to pdf. save to html brings a pop-up "printing failed. is file open in another application" (it's not)

**Comment by nicebikemate** [comment]
Seems as if this might have been something to do with our network and profiles. Moving the package folder to and external hdd seems to have fixed the issue

**Comment by ksobon** [comment]
Thanks for reporting this. I would like to understand more about the issue and the fix you proposed. So the package crashes when its located in the AppData folder, but it stops when you move it to a Network location? Can you elaborate?

**Comment by nicebikemate** [comment]
Yer no problem, i'll do my best to explain though I suspect the origins of this issue might be particular to our company rather than anything to do with your coding.

The package was originally installed to it's default location and i'd attempted to re-install it to the same place multiple times. I'd upgraded my windows, reinstalled dynamo, deactivated the other addings etc etc but it wasn't going away. The error _"The process cannot access the file 'C:\Users\RobertS\AppData\Roaming\Dynamo\Dynamo Revit\2.2\packages\Archi-lab_Mandrill\bin\eowp.exe' because it is being used by another process."_ coupled with other non-Revit issues we've been having (trying to write to a file sometimes saying that the file was locked, opening a file saying and again saying it was locked etc) made me think it might be worth trying to install it somewhere where external from our company settings.

My suspicion is that it might have something to do with our permissions writing to the C:/ though honestly that is a fairly uneducated guess. As unhelpful as our IT support as been with this issue, they obviously still know considerably more than me.

I understand that this probably isn't helpful to you much, but I think that you can probably put it in the 'nothing to do with Mandrill' pile.

Just as an aside, my Dynamo is also exceptionally sluggish to respond when searching for nodes etc (I've been using it since I saw you present it at the London Uni South Bank in something like 2014) and this is the first time it's been an issue (started a new job) so again this kind of reinforces the idea that the issue is internal to my company rather than anything else.

All the best,
Rob
